gm12878_clone4Aligned.out.samtool.rmdup.allele.counts.bed
gm12878_clone4Aligned.out.samtool.rmdup.minus.allele.counts.bed
gm12878_clone4Aligned.out.samtool.rmdup.plus.allele.counts.bed
gm12878_clone5Aligned.out.samtool.rmdup.allele.counts.bed
gm12878_clone5Aligned.out.samtool.rmdup.minus.allele.counts.bed
gm12878_clone5Aligned.out.samtool.rmdup.plus.allele.counts.bed

eb3_2_clone10Aligned.out.samtool.rmdup.allele.counts.bed
eb3_2_clone10Aligned.out.samtool.rmdup.minus.allele.counts.bed
eb3_2_clone10Aligned.out.samtool.rmdup.plus.allele.counts.bed
eb3_2_clone13Aligned.out.samtool.rmdup.allele.counts.bed
eb3_2_clone13Aligned.out.samtool.rmdup.minus.allele.counts.bed
eb3_2_clone13Aligned.out.samtool.rmdup.plus.allele.counts.bed
eb3_2_clone15Aligned.out.samtool.rmdup.allele.counts.bed
eb3_2_clone15Aligned.out.samtool.rmdup.minus.allele.counts.bed
eb3_2_clone15Aligned.out.samtool.rmdup.plus.allele.counts.bed
eb3_2_clone2Aligned.out.samtool.rmdup.allele.counts.bed
eb3_2_clone2Aligned.out.samtool.rmdup.minus.allele.counts.bed
eb3_2_clone2Aligned.out.samtool.rmdup.plus.allele.counts.bed
eb3_2_clone3Aligned.out.samtool.rmdup.allele.counts.bed
eb3_2_clone3Aligned.out.samtool.rmdup.minus.allele.counts.bed
eb3_2_clone3Aligned.out.samtool.rmdup.plus.allele.counts.bed
eb3_2_clone4Aligned.out.samtool.rmdup.allele.counts.bed
eb3_2_clone4Aligned.out.samtool.rmdup.minus.allele.counts.bed
eb3_2_clone4Aligned.out.samtool.rmdup.plus.allele.counts.bed
